apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-nginx-ingress
spec:
  ingressClassName: nginx    # ðŸ‘ˆ Must match the IngressClass name
  rules:
  - host: web-app-nginx.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-app-nginx
            port:
              number: 80
